
platform :ios, '12.0'
use_frameworks!

target 'UScrollView_Example' do
  pod 'UScrollView', :path => '../'
  pod 'TinyConstraints', '~> 4.0.0'

  target 'UScrollView_Tests' do
    inherit! :search_paths

    
  end
end
